// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace ArenaGameplayTags {
	/** Input Tags **/
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe);

	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe);

	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Roll);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SwitchTarget);

	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SpecialWeaponAbility_Light);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SpecialWeaponAbility_Heavy);

	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld_Block);

	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable_TargetLock);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable_Rage);


	/** Player Tags **/
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe); 
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Roll);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Block);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_TargetLock);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Rage);

	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_SpecialWeaponAbility_Light);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_SpecialWeaponAbility_Heavy);

	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_CoolDown_SpecialWeaponAbility_Light);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_CoolDown_SpecialWeaponAbility_Heavy);

	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);

	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Axe);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_HitPause);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SuccessfulBlock);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SwitchTarget_Left);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SwitchTarget_Right);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_ActivateRage);

	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Rolling);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Blocking);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_TargetLock);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Rage_Activating);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Rage_Active);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Rage_Full);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Rage_None);

	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Heavy);

	/** Enemy Tags **/
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_SummonEnemies);

	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);

	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Event_SummonEnemies);

	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Strafing);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_UnderAtack);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_UnblockableAttack);

	/** Shared Tags **/
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);

	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_SpawnProjectile);

	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);

	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Dead);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Front);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Back);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Left);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Right);
	ARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Invincible);
}
